In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [4]:
data = pd.read_csv("data/energydata_complete.csv")
data.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [34]:
x = data[['Windspeed','Press_mm_hg','T_out']]
x

Windspeed  Press_mm_hg      T_out
0       7.000000        733.5   6.600000
1       6.666667        733.6   6.483333
2       6.333333        733.7   6.366667
3       6.000000        733.8   6.250000
4       5.666667        733.9   6.133333
...          ...          ...        ...
19730   3.333333        755.2  22.733333
19731   3.500000        755.2  22.600000
19732   3.666667        755.2  22.466667
19733   3.833333        755.2  22.333333
19734   4.000000        755.2  22.200000

[19735 rows x 3 columns]

In [35]:
y = data['Appliances']
y

0         60
1         60
2         50
3         50
4         60
        ... 
19730    100
19731     90
19732    270
19733    420
19734    430
Name: Appliances, Length: 19735, dtype: int64

In [36]:
Xnp = x.to_numpy()
Xnp

array([[  7.        , 733.5       ,   6.6       ],
       [  6.66666667, 733.6       ,   6.48333333],
       [  6.33333333, 733.7       ,   6.36666667],
       ...,
       [  3.66666667, 755.2       ,  22.46666667],
       [  3.83333333, 755.2       ,  22.33333333],
       [  4.        , 755.2       ,  22.2       ]])

In [37]:
Ynp = y.to_numpy()
Ynp

array([ 60,  60,  50, ..., 270, 420, 430], dtype=int64)

In [38]:
from sklearn.model_selection import train_test_split # suddivide le osservazioni nei due insiemi

X_train, X_test, y_train, y_test = train_test_split(Xnp, Ynp, 
                                                    test_size = 0.33, 
                                                    random_state = 123) # fix random seed for replicability

In [39]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((13222, 3), (13222,), (6513, 3), (6513,))

In [40]:
print(X_train[:10])
print(f'y_train = {y_train[:10]}')

[[ 7.66666667e+00  7.49066667e+02  1.41000000e+01]
 [ 2.00000000e+00  7.57700000e+02  5.00000000e+00]
 [ 4.83333333e+00  7.54383333e+02  8.65000000e+00]
 [ 9.00000000e+00  7.53883333e+02  1.04666667e+01]
 [ 2.00000000e+00  7.64866667e+02  6.13333333e+00]
 [ 1.16666667e+00  7.56066667e+02 -6.00000000e-01]
 [ 2.50000000e+00  7.55400000e+02 -1.00000000e-01]
 [ 2.50000000e+00  7.60300000e+02 -1.85000000e+00]
 [ 1.00000000e+00  7.58016667e+02  6.18333333e+00]
 [ 2.50000000e+00  7.44300000e+02  1.90500000e+01]]
y_train = [120  60  70  40 420  80  50  90  60  50]


In [41]:
#Using sklearn package to model data :
regr = linear_model.LinearRegression()
regr.fit(X_train,y_train)
predict = regr.predict(X_test)

print(f'dati predetti dal metodo = {predict[:10].round(decimals=2)}') # dati predetti dal metodo
print(f'dati reali presenti nel dataset di test = {y_test[:10]}') # dati effettivi presenti nel test set

dati predetti dal metodo = [ 89.69  87.91  94.22  79.14 109.3  102.    88.98  82.02  97.45 123.65]
dati reali presenti nel dataset di test = [ 70  50  50  50  60 100 250 100 100  60]


In [42]:
from sklearn.metrics import r2_score, mean_squared_error

# The coefficients
print('Coefficients: \n', regr.coef_)

# The mean squared error
print('Mean squared error: %.2f' %mean_squared_error(y_test, predict))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' %r2_score(y_test, predict))

Coefficients: 
 [ 3.01119769 -0.01414162  1.5664262 ]
Mean squared error: 10305.99
Coefficient of determination: 0.02
